name: Build Release Container
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          cd docker
          docker build -t ghcr.io/coleifer/sqlite-web:${{  github.ref_name }} .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Upload versioned container to registry
        run: docker push ghcr.io/coleifer/sqlite-web:${{  github.ref_name }}
