name: Build latest Container
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          cd docker
          docker build -t ghcr.io/coleifer/sqlite-web:latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Upload latest container to registry
        run: docker push ghcr.io/coleifer/sqlite-web:latest
